databases:
  - name: budget
    databaseName: budget_production
    user: ba_user

services:
  - type: web
    name: budget
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false