databases:
  - name: postgres
    ipAllowList: []
    databaseName: budget_development
    user: Budget-App

services:
  - type: web
    name: Budget-App
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false